version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/manabee
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 600
      runas: root
    - location: scripts/start_server
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: root

